// Vitest suite proving search and column filtering happen before server-side pagination is applied.
import { describe, it, expect, beforeEach } from 'vitest';
import { mockServer } from '../features/inventory/lib/mockServer';
import type { InventoryRecord } from '../features/inventory/types/inventory.types';

describe('mockServer.ts - Server-Side Data Layer Contract', () => {
  const sampleRecords: InventoryRecord[] = [
    {
      id: 'rec_1',
      sku: 'SKU-ALPHA-100',
      name: 'Industrial Microcontroller A1',
      barcode: '100000000001',
      category: 'Electronics',
      subcategory: 'Microcontrollers',
      brand: 'TechCorp',
      tags: ['electronics'],
      variant: 'Standard',
      unit: 'pcs',
      warehouse: 'WH-NORTH-01',
      qtyOnHand: 50,
      qtyReserved: 5,
      qtyAvailable: 45,
      reorderPoint: 20,
      reorderQty: 100,
      binLocation: 'A-1-1',
      unitCost: 10,
      listPrice: 20,
      salePrice: 20,
      marginPercent: 50,
      taxRate: 0,
      discountPercent: 0,
      priceTier: 'Standard',
      supplierId: 'SUP-001',
      supplierName: 'TechCorp Supplier',
      supplierSku: 'SUP-SKU-100',
      leadTimeDays: 7,
      minOrderQty: 10,
      lastPurchaseDate: '2026-01-01',
      status: 'HEALTHY',
      isPerishable: false,
      expiryDate: null,
      weightKg: 0.5,
      dimensionsCm: '10x10x5',
      isFragile: false,
      hazardClass: 'None',
      bayNumber: 'B1',
      shelfNumber: 'S1',
      countryOfOrigin: 'USA',
      hsCode: '8544.42',
      warrantyMonths: 12,
      packageType: 'Box',
      handlingInstructions: 'Standard',
      isReturnable: true,
      minStorageTempC: -10,
      maxStorageTempC: 40,
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
      createdBy: 'Test User',
      updatedBy: 'Test User',
      lastSoldAt: '2026-01-01T00:00:00Z',
      syncStatus: 'Synced',
      totalStockValue: 500,
      daysOfSupply: 30,
      isLowStock: false,
    },
    {
      id: 'rec_2',
      sku: 'SKU-BETA-200',
      name: 'Heavy Duty Bearing B2',
      barcode: '100000000002',
      category: 'Industrial Hardware',
      subcategory: 'Bearings',
      brand: 'HeavyGear',
      tags: ['hardware'],
      variant: 'Pro',
      unit: 'pcs',
      warehouse: 'WH-SOUTH-02',
      qtyOnHand: 15,
      qtyReserved: 2,
      qtyAvailable: 13,
      reorderPoint: 30,
      reorderQty: 50,
      binLocation: 'B-2-2',
      unitCost: 15,
      listPrice: 35,
      salePrice: 35,
      marginPercent: 57.1,
      taxRate: 0,
      discountPercent: 0,
      priceTier: 'Standard',
      supplierId: 'SUP-002',
      supplierName: 'GearSupply Inc',
      supplierSku: 'SUP-SKU-200',
      leadTimeDays: 14,
      minOrderQty: 5,
      lastPurchaseDate: '2026-01-05',
      status: 'LOW_STOCK',
      isPerishable: false,
      expiryDate: null,
      weightKg: 2.0,
      dimensionsCm: '15x15x10',
      isFragile: false,
      hazardClass: 'None',
      bayNumber: 'B2',
      shelfNumber: 'S2',
      countryOfOrigin: 'Germany',
      hsCode: '8482.10',
      warrantyMonths: 24,
      packageType: 'Box',
      handlingInstructions: 'Standard',
      isReturnable: true,
      minStorageTempC: -10,
      maxStorageTempC: 40,
      createdAt: '2026-01-02T00:00:00Z',
      updatedAt: '2026-01-02T00:00:00Z',
      createdBy: 'Test User',
      updatedBy: 'Test User',
      lastSoldAt: '2026-01-02T00:00:00Z',
      syncStatus: 'Synced',
      totalStockValue: 225,
      daysOfSupply: 10,
      isLowStock: true,
    },
    {
      id: 'rec_3',
      sku: 'SKU-ALPHA-300',
      name: 'Precision Sensor Alpha X',
      barcode: '100000000003',
      category: 'Electronics',
      subcategory: 'Sensors',
      brand: 'TechCorp',
      tags: ['electronics'],
      variant: 'Compact',
      unit: 'pcs',
      warehouse: 'WH-NORTH-01',
      qtyOnHand: 200,
      qtyReserved: 10,
      qtyAvailable: 190,
      reorderPoint: 40,
      reorderQty: 100,
      binLocation: 'A-1-2',
      unitCost: 25,
      listPrice: 50,
      salePrice: 50,
      marginPercent: 50,
      taxRate: 0,
      discountPercent: 0,
      priceTier: 'Standard',
      supplierId: 'SUP-001',
      supplierName: 'TechCorp Supplier',
      supplierSku: 'SUP-SKU-300',
      leadTimeDays: 7,
      minOrderQty: 10,
      lastPurchaseDate: '2026-01-10',
      status: 'HEALTHY',
      isPerishable: false,
      expiryDate: null,
      weightKg: 0.2,
      dimensionsCm: '5x5x3',
      isFragile: true,
      hazardClass: 'None',
      bayNumber: 'B1',
      shelfNumber: 'S2',
      countryOfOrigin: 'Japan',
      hsCode: '9031.80',
      warrantyMonths: 12,
      packageType: 'Box',
      handlingInstructions: 'Handle with care',
      isReturnable: true,
      minStorageTempC: -10,
      maxStorageTempC: 40,
      createdAt: '2026-01-03T00:00:00Z',
      updatedAt: '2026-01-03T00:00:00Z',
      createdBy: 'Test User',
      updatedBy: 'Test User',
      lastSoldAt: '2026-01-03T00:00:00Z',
      syncStatus: 'Synced',
      totalStockValue: 5000,
      daysOfSupply: 45,
      isLowStock: false,
    },
    {
      id: 'rec_4',
      sku: 'SKU-GAMMA-400',
      name: 'Safety Glasses Pro',
      barcode: '100000000004',
      category: 'Safety Equipment',
      subcategory: 'PPE',
      brand: 'SafeGuard',
      tags: ['safety'],
      variant: 'Standard',
      unit: 'pcs',
      warehouse: 'WH-EAST-05',
      qtyOnHand: 500,
      qtyReserved: 20,
      qtyAvailable: 480,
      reorderPoint: 100,
      reorderQty: 200,
      binLocation: 'C-3-1',
      unitCost: 4,
      listPrice: 12,
      salePrice: 12,
      marginPercent: 66.7,
      taxRate: 0,
      discountPercent: 0,
      priceTier: 'Standard',
      supplierId: 'SUP-004',
      supplierName: 'SafeGuard Corp',
      supplierSku: 'SUP-SKU-400',
      leadTimeDays: 5,
      minOrderQty: 50,
      lastPurchaseDate: '2026-01-12',
      status: 'HEALTHY',
      isPerishable: false,
      expiryDate: null,
      weightKg: 0.1,
      dimensionsCm: '18x8x5',
      isFragile: false,
      hazardClass: 'None',
      bayNumber: 'B3',
      shelfNumber: 'S1',
      countryOfOrigin: 'Taiwan',
      hsCode: '9004.90',
      warrantyMonths: 6,
      packageType: 'Box',
      handlingInstructions: 'Standard',
      isReturnable: true,
      minStorageTempC: -10,
      maxStorageTempC: 40,
      createdAt: '2026-01-04T00:00:00Z',
      updatedAt: '2026-01-04T00:00:00Z',
      createdBy: 'Test User',
      updatedBy: 'Test User',
      lastSoldAt: '2026-01-04T00:00:00Z',
      syncStatus: 'Synced',
      totalStockValue: 2000,
      daysOfSupply: 60,
      isLowStock: false,
    },
    {
      id: 'rec_5',
      sku: 'SKU-ALPHA-500',
      name: 'High Voltage Cable Alpha',
      barcode: '100000000005',
      category: 'Electronics',
      subcategory: 'Cables',
      brand: 'TechCorp',
      tags: ['electronics'],
      variant: 'Heavy Duty',
      unit: 'm',
      warehouse: 'WH-NORTH-01',
      qtyOnHand: 1200,
      qtyReserved: 100,
      qtyAvailable: 1100,
      reorderPoint: 200,
      reorderQty: 500,
      binLocation: 'A-2-1',
      unitCost: 8,
      listPrice: 18,
      salePrice: 18,
      marginPercent: 55.6,
      taxRate: 0,
      discountPercent: 0,
      priceTier: 'Standard',
      supplierId: 'SUP-001',
      supplierName: 'TechCorp Supplier',
      supplierSku: 'SUP-SKU-500',
      leadTimeDays: 10,
      minOrderQty: 100,
      lastPurchaseDate: '2026-01-15',
      status: 'HEALTHY',
      isPerishable: false,
      expiryDate: null,
      weightKg: 15.0,
      dimensionsCm: '50x50x20',
      isFragile: false,
      hazardClass: 'None',
      bayNumber: 'B1',
      shelfNumber: 'S4',
      countryOfOrigin: 'USA',
      hsCode: '8544.49',
      warrantyMonths: 36,
      packageType: 'Spool',
      handlingInstructions: 'Heavy spool',
      isReturnable: false,
      minStorageTempC: -20,
      maxStorageTempC: 50,
      createdAt: '2026-01-05T00:00:00Z',
      updatedAt: '2026-01-05T00:00:00Z',
      createdBy: 'Test User',
      updatedBy: 'Test User',
      lastSoldAt: '2026-01-05T00:00:00Z',
      syncStatus: 'Synced',
      totalStockValue: 9600,
      daysOfSupply: 90,
      isLowStock: false,
    },
  ];

  beforeEach(() => {
    mockServer.setDatasetDirectly(sampleRecords);
  });

  it('proves global search filtering occurs BEFORE pagination is applied', async () => {
    // There are 3 records containing "ALPHA" in SKU/Name: rec_1, rec_3, rec_5.
    // If pagination (pageSize: 2, page: 0) was applied BEFORE search, page 0 would only see rec_1 and rec_2.
    // Search for "ALPHA" on page 0 with pageSize 2 should return 2 rows out of totalCount = 3 matching rows!
    const resultPage0 = await mockServer.listRecords({
      page: 0,
      pageSize: 2,
      search: 'ALPHA',
    });

    expect(resultPage0.totalCount).toBe(3);
    expect(resultPage0.rows.length).toBe(2);
    expect(resultPage0.totalPages).toBe(2);
    expect(resultPage0.rows.every((r) => r.sku.includes('ALPHA') || r.name.includes('Alpha'))).toBe(true);

    // Page 1 should fetch the remaining 1 matching "ALPHA" row
    const resultPage1 = await mockServer.listRecords({
      page: 1,
      pageSize: 2,
      search: 'ALPHA',
    });

    expect(resultPage1.totalCount).toBe(3);
    expect(resultPage1.rows.length).toBe(1);
    expect(resultPage1.rows[0].sku.includes('ALPHA') || resultPage1.rows[0].name.includes('Alpha')).toBe(true);
  });

  it('proves column level filtering occurs BEFORE pagination is applied', async () => {
    // Filter by category = "Electronics" (rec_1, rec_3, rec_5 = 3 items)
    const result = await mockServer.listRecords({
      page: 0,
      pageSize: 2,
      filters: [{ field: 'category', operator: 'equals', value: 'Electronics' }],
    });

    expect(result.totalCount).toBe(3);
    expect(result.rows.length).toBe(2);
    expect(result.rows.every((r) => r.category === 'Electronics')).toBe(true);
  });

  it('proves statusFilter narrows down dataset accurately before pagination', async () => {
    const result = await mockServer.listRecords({
      page: 0,
      pageSize: 10,
      statusFilter: 'LOW_STOCK',
    });

    expect(result.totalCount).toBe(1);
    expect(result.rows[0].sku).toBe('SKU-BETA-200');
    expect(result.statusCounts.LOW_STOCK).toBe(1);
  });
});
